### ISSUE TITLE
can you share some description how to use ?

### ISSUE THREAD

**Issue by Sandy4321** [igorarduin/RESGen_EU#2]
great code 
seems to be unique in git

can you share some description how to use ?

**Comment by igorarduin** [comment]
You can find some documentation in my thesis here:
https://www.google.com/url?sa=t&source=web&rct=j&url=http://pierrepinson.com/docs/arduin16.pdf&ved=2ahUKEwjnot2oztDwAhW7h_0HHZcfA0IQFjACegQIChAC&usg=AOvVaw3K_6kEKuBmBnFHuZ1_eaGN
